version: "3"

services:
  web:
    build: fastapi
    ports:
      - 10000:8000
    volumes:
      - ./fastapi:/app
    networks:
      - tutorial-net
      - ollama-net

  ollama:
    build: ollama
    ports:
      - 11434:11434
    volumes:
      - ollama-vol:/ollama
    networks:
      - ollama-net
    entrypoint: ["/usr/bin/bash", "/pull-llama3.sh"]

  nginx:
    build: nginx   
    ports:
      - 80:80        
    networks:
      - ollama-net
    depends_on:
      - ollama
      - web

networks:
  ollama-net:
    driver: bridge
  tutorial-net:
    driver: bridge

volumes:
  ollama-vol:
    driver: local

