services:
  - type: web
    name: ollama_llm_file_analyzer
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: "11434"
    ports:
      - port: 10000
        protocol: tcp
        targetPort: 11434

